### ISSUE TITLE
Radio used instead of Radius

### ISSUE THREAD

**Issue by AnnieGitUrGun** [techjb/Vector-Tiles-Google-Maps#1]
Hi! First, let me say thank you for all your hard work creating this fantastic library! Great stuff!

I was attempting to add a zoom level dependent radius to a point layer and ran into a language issue. You used 'radio' instead of radius (Spanish instead of English). It was easy enough for me to realize what was going on but, if you're going for consistency, the English word should be used. I can submit a pull request if you'd like.

Thanks again for the wonderful library!

**Comment by techjb** [comment]
Yes, you are right. I used the spanish word instead of english. You can send the pull request.
Regards.

**Comment by techjb** [comment]
The library has been updated and replaced "radio" by "radius"
