### ISSUE TITLE
Capability to Add Predefined Style URL

### ISSUE THREAD

**Issue by iqnaul** [techjb/Vector-Tiles-Google-Maps#13]
Hi @techjb 

Appreciate your work on this, just wondering whether I can use this library to add predefined MVT Style that I already have. So in my use case, I have defined a style in a JSON and I have this JSON is accessible from an internal web URL that I setup previously. Can I use that URL so that it can render the Vector Tile maps correctly?

Thank you

**Comment by techjb** [comment]
Yes, you can initialize the library with your own style. Check the source code of this example:
[https://techjb.github.io/Vector-Tiles-Google-Maps/examples/styles.html](https://techjb.github.io/Vector-Tiles-Google-Maps/examples/styles.html)
You should read the style in json firstly and then initialize the library with it. Also you can also change the style dinamically.
