### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by robertovaldesperez** [techjb/Vector-Tiles-Google-Maps#5]
Good morning @techjb, can you generate an npm package?

**Comment by techjb** [comment]
Sorry, but Im vanilla developer...

**Comment by plgagnon2** [comment]
sad

**Comment by plgagnon2** [comment]
I think someone is working on it https://github.com/galihrivanto/Vector-Tiles-Google-Maps

**Comment by robertovaldesperez** [comment]
thanks a lot @plgagnon2 @techjb
