### ISSUE TITLE
Draw Point Text

### ISSUE THREAD

**Issue by Noruka** [techjb/Vector-Tiles-Google-Maps#6]
Buenas, querría saber si es posible implementar una funcionalidad para que cuando pintemos un punto, se pueda pasar un texto para que se pinte el texto. Viendo el código, la parte de Feature hay un _DrawPoint, igual ahí es donde habría que controlar esto. Saludos.

**Comment by techjb** [comment]
En la librería original https://github.com/SpatialServer/Leaflet.MapboxVectorTile había la posibilidad de añadir "labels". Sin embargo, esta funcionalidad se eliminó en la librería que desarrollé por diversos motivos.

**Comment by robertovaldesperez** [comment]
@techjb buenas, desconozco los motivos por el cual se elimino la funcionalidad, pero seria interesante dar la posibilidad de añadir labels, si no puedes añadir Layers que contengan esa información.

**Comment by techjb** [comment]
Tomo nota. Pero ahora mismo no voy a poder implementarlo, no tengo tiempo.

**Comment by techjb** [comment]
Se ha añadido la opción de pasar como parámetro una función "customDraw". De esta forma ahora es posible tener total control sobre lo que se dibuja en el canvas y te permitirá dibujar textos con context2d.fillText("text",x,y).
Se ha añadido también un ejemplo de uso:
[https://techjb.github.io/Vector-Tiles-Google-Maps/examples/custom-draw.html](https://techjb.github.io/Vector-Tiles-Google-Maps/examples/custom-draw.html)

**Comment by robertovaldesperez** [comment]
@techjb muchísimas gracias

**Comment by Noruka** [comment]
Perfecto muchísimas gracias! @techjb
