### ISSUE TITLE
Is there any way to check whether vector tiles are fully rendered or not?

### ISSUE THREAD

**Issue by iamtekson** [techjb/Vector-Tiles-Google-Maps#9]
Hi @techjb, Thank you very much for this package. I found this package very helpful for rendering the vector tiles in my Google map.

Is there any way to check whether visible vector tiles are fully rendered or not in the browser? Please kindly guide me.

**Comment by techjb** [comment]
At the moment, there is no way to know if a layer has already been rendered. Vector tiles are loaded asynchronously, so as they are downloaded, they are rendered. Perhaps you can cycle through all the tiles being displayed, and if it contains the tilecontext, then it has been rendered. Something similar to what is done in the DrawTile function of MVTSource.js.

 var id = this.getTileId(zoom, coord.x, coord.y);
var tileContext = this._tilesDrawn[id];
if(tileContext){
 return true;
}

**Comment by iamtekson** [comment]
Hi, I just send a PR. Please review and merge it. Thank you!
